---
title: "Analysis for Project"
output:
    pdf_document:
    toc: yes
    toc_depth: '4'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, message=FALSE)
source("useful_functions.R")
library(readr)
load("output/analytical_data.RData")
library(ggplot2)
library(texreg)
```

#Univariate distributions

```{r maternal-mortality, fig.cap="Distribution of Generation"}
ggplot(mat_mort, aes(x=year, y=mmr_race, color=region))+
  geom_point()+
  geom_smooth(se=FALSE, span=1)+
  theme_bw()
```

```{r insurance-diff, fig.cap="Distribution of Generation"}
ggplot(mat_mort, aes(x=year, y=diff_coverage, color=region))+
  geom_point()+
  geom_smooth(se=FALSE, span=1)+
  geom_hline(yintercept = 0, linetype=2)+
  theme_bw()
```

```{r mmr-white, fig.cap="Distribution of Generation"}
ggplot(mat_mort, aes(x=year, y=mmr_white, color=region))+
  geom_point()+
  geom_smooth(se=FALSE, span=1)+
  theme_bw()
```
```{r mmr-black, fig.cap="Distribution of Generation"}
ggplot(mat_mort, aes(x=year, y=mmr_black, color=region))+
  geom_point()+
  geom_smooth(se=FALSE, span=1)+
  theme_bw()
```



```{r insurance-diff2, fif.cap="Distribution of Generation"}
ggplot(mat_mort, aes(x=year, y=health_coverage_white, color=region))+
  geom_point()+
  geom_smooth(se=FALSE, span=1)+
  theme_bw()
```
```{r insurance-diff3, fif.cap="Distribution of Generation"}
ggplot(mat_mort, aes(x=year, y=health_coverage_black, color=region))+
  geom_point()+
  geom_smooth(se=FALSE, span=1)+
  theme_bw()
```


#bivariate plots


```{r maternal mortality, echo=FALSE, fig.cap="", fig.align="center"}
ggplot(mat_mort, aes(x=diff_coverage, y=mmr_race))+
  geom_point(aes(color=region))+
  geom_smooth(method="lm", se=FALSE)+
  geom_smooth(aes(color=region), method="lm", se=FALSE)+
  theme_bw()
```

```{r maternalwhite, echo=FALSE, fig.cap="", fig.align="center"}
ggplot(mat_mort, aes(x=health_coverage_white, y=mmr_white))+
  geom_point(aes(color=region))+
  geom_smooth(method="lm", se=FALSE)+
  geom_smooth(aes(color=region), method="lm", se=FALSE)+
  theme_bw()
```

```{r maternalblack, echo=FALSE, fig.cap="", fig.align="center"}
ggplot(mat_mort, aes(x=health_coverage_black, y=mmr_black))+
  geom_point(aes(color=region))+
  geom_smooth(method="lm", se=FALSE)+
  geom_smooth(aes(color=region), method="lm", se=FALSE)+
  theme_bw()
```




#Run some models

```{r model-white, results= 'asis'}
model.olswhite <- lm(log(mmr_white)~health_coverage_white, data=mat_mort)
#summary(model.ols)
model.fixregionwhite <- update(model.olswhite, .~.+region)
model.fixbothwhite <- update(model.fixregionwhite, .~.+as.factor(year))
#summary(model.fixboth)
screenreg(list(model.olswhite, model.fixregionwhite, model.fixbothwhite), digits=3)
```
```{r model-black, results= 'asis'}
model.olsblack <- lm(log(mmr_black)~health_coverage_black, data=mat_mort)
#summary(model.ols)
model.fixregionblack <- update(model.olsblack, .~.+region)
model.fixbothblack <- update(model.fixregionblack, .~.+as.factor(year))
#summary(model.fixboth)
screenreg(list(model.olsblack, model.fixregionblack, model.fixbothblack), digits=3)
```

```{r model, results= 'asis'}
model.ols <- lm(log(mmr_race)~diff_coverage, data=mat_mort)
summary(model.ols)
model.fixregion <- update(model.ols, .~.+region)
model.fixboth <- update(model.fixregion, .~.+as.factor(year))
summary(model.fixboth)
htmlreg(list(model.ols, model.fixregion, model.fixboth), digits=3)
```

